import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import {ReactNode} from "react";
import {getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";
import Footer from "@/components/layouts/Footer";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "V-COMP",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

type Props = {
  children: ReactNode;
  params: {locale: string};
};

export default async function RootLayout({children, params: {locale}}: Props) {
  const message = await getMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={message}>
          <Header />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
